#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to another URL

# Create redirection configuration
cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOL

# Restart Nginx using service command
service nginx restart
