#!/usr/bin/env bash
# Script that hates to be rejected

sudo touch /var/run/myscript.pid
sudo sh -c 'echo $$ > /var/run/myscript.pid'

sigterm(){
	echo I hate the kill command
	sudo rm /var/run/myscript.pid
	exit
}

sigint(){
	echo Y U no love me?!
}

sigquit(){
	sudo rm /var/run/myscript.pid
	exit
}

trap sigterm SIGTERM
trap sigint SIGINT
trap sigquit SIGQUIT

while true
do
	echo To infinity and beyond
	sleep 2
done
