#!/usr/bin/env bash
# Displays the PID and process name of processes containing the word bash
#!/usr/bin/env bash
# Displays the PID and the process name of bash processes and scripts running through bash
pgrep -a bash | awk '/bash$/ {print $1, $2} /bash .*\// {print $1, $2}'
