#!/usr/bin/env bash

# Read the /etc/passwd file and display username, user id, and home directory path for each user

while IFS=":" read -r username _ userid _ home_directory x; do
    echo "$username:$userid:$home_directory"
done < /etc/passwd
