#!/usr/bin/env bash

# Read the /etc/passwd file and tell a story for each user

while IFS=":" read -r username x userid group_id info home_directory shell; do
    echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $info"
done < /etc/passwd
