#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it's executed on.

ipv4_addresses=$(ifconfig | grep -Eo 'inet ([0-9]{1,3}\.){3}[0-9]{1,3}' | awk '{print $2}')
echo "$ipv4_addresses"
