#!/usr/bin/env bash
# A  Bash script that creates an RSA key pair.
# Define the key name and passphrase
KEY_NAME="school"
PASSPHRASE="betty"
BITS=4096

# Generate the RSA key pair
ssh-keygen -t rsa -b $BITS -f ~/.ssh/$KEY_NAME -N $PASSPHRASE
